### ISSUE TITLE
Past score not showing

### ISSUE THREAD

**Issue by Prakash2403** [saurabhjn76/Capstone-Stage-2#1]
As soon as I log out and login again, my past scores are not showing in profile. Is it intentional?

**Comment by saurabhjn76** [comment]
Yes, it is intentional. Since user may log in from another id, thus it is neccesary to clear database.
For the time being it is more of  one session based scores.

**Comment by Prakash2403** [comment]
A suggestion: You could use firebase for maintaining scores for each user id.

**Comment by saurabhjn76** [comment]
Thanks for the suggestion, I already implemented the same at some places. Since this was Udacity Capstone project, it was mandatory to implement some of the methods. The main purpose was to implement content providers and then move data into views through Loaders.  I hope this answers you query.
